import { EventAttendance, PFIEvent, StudentAuditEntry, UserProfile } from './types';

export const MOCK_PROFILES: UserProfile[] = [
  {
    id: 'usr-student-01',
    matricula: 'UP220419',
    nombre: 'Sofía',
    apellidos: 'Méndez Cota',
    carrera: 'LICENCIATURA EN DERECHO',
    cuatrimestre: 3,
    periodo_ingreso: '2022-2',
    email: 'sofia.mendez@unipaz.edu.mx',
    role: 'estudiante',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    qr_secret: '4a6b8c9d-1111-4444-9999-sofiamendez01',
    tiene_beca: true,
    tipo_beca: 'Excelencia Académica (Promedio 9.6 - 10.0)',
    porcentaje_beca: 50,
    promedio_academico: 9.65,
    puntos_beca_meta_cuatrimestral: 1000,
    created_at: '2022-08-15T09:00:00Z',
  },
  {
    id: 'usr-student-02',
    matricula: 'UP210382',
    nombre: 'Carlos',
    apellidos: 'Valenzuela Arce',
    carrera: 'LICENCIATURA EN ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES',
    cuatrimestre: 7,
    periodo_ingreso: '2021-1',
    email: 'carlos.valenzuela@unipaz.edu.mx',
    role: 'estudiante',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    qr_secret: '7b8c9d0e-2222-5555-8888-carlosvalenzuela02',
    tiene_beca: true,
    tipo_beca: 'Deportiva (Garzas UNIPAZ)',
    porcentaje_beca: 75,
    promedio_academico: 8.92,
    puntos_beca_meta_cuatrimestral: 1000,
    created_at: '2021-02-10T09:00:00Z',
  },
  {
    id: 'usr-student-03',
    matricula: 'UP230554',
    nombre: 'Mariana',
    apellidos: 'Castro Beltrán',
    carrera: 'LICENCIATURA EN PSICOLOGÍA',
    cuatrimestre: 2,
    periodo_ingreso: '2023-2',
    email: 'mariana.castro@unipaz.edu.mx',
    role: 'estudiante',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    qr_secret: '9c0d1e2f-3333-6666-7777-marianacastro03',
    tiene_beca: false,
    created_at: '2023-08-20T09:00:00Z',
  },
  {
    id: 'usr-student-04',
    matricula: 'UP240112',
    nombre: 'Alejandro',
    apellidos: 'Romero Meza',
    carrera: 'LICENCIATURA EN ADMINISTRACIÓN',
    cuatrimestre: 3,
    periodo_ingreso: '2024-1',
    email: 'alejandro.romero@unipaz.edu.mx',
    role: 'estudiante',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    qr_secret: '1a2b3c4d-4444-7777-8888-alejandroromero04',
    tiene_beca: true,
    tipo_beca: 'Apoyo Departamental - Biblioteca',
    porcentaje_beca: 50,
    promedio_academico: 9.3,
    puntos_beca_meta_cuatrimestral: 1000,
    es_becario_departamental: true,
    departamento_beca: 'Biblioteca',
    horas_departamentales_semanales: 10,
    cumplimiento_departamental_acreditado: true,
    fecha_acreditacion_departamental: '2026-08-15',
    puntos_departamentales_otorgados: 1000,
    created_at: '2024-01-15T09:00:00Z',
  },
  {
    id: 'usr-student-05',
    matricula: 'UP220891',
    nombre: 'Valeria',
    apellidos: 'Higuera Lucero',
    carrera: 'LICENCIATURA EN TRABAJO SOCIAL',
    cuatrimestre: 5,
    periodo_ingreso: '2022-1',
    email: 'valeria.higuera@unipaz.edu.mx',
    role: 'estudiante',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    qr_secret: '2b3c4d5e-5555-8888-9999-valeriahiguera05',
    tiene_beca: true,
    tipo_beca: 'Apoyo Departamental - INDE',
    porcentaje_beca: 60,
    promedio_academico: 9.85,
    puntos_beca_meta_cuatrimestral: 1000,
    es_becario_departamental: true,
    departamento_beca: 'INDE (Instituto de Investigación e Innovación)',
    horas_departamentales_semanales: 12,
    cumplimiento_departamental_acreditado: false,
    puntos_departamentales_otorgados: 1000,
    created_at: '2022-02-15T09:00:00Z',
  },
  {
    id: 'usr-student-06',
    matricula: 'UP200155',
    nombre: 'Fernando',
    apellidos: 'Salazar Trasviña',
    carrera: 'LICENCIATURA EN DERECHO',
    cuatrimestre: 8,
    periodo_ingreso: '2020-2',
    email: 'fernando.salazar@unipaz.edu.mx',
    role: 'estudiante',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    qr_secret: '3c4d5e6f-6666-9999-0000-fernandosalazar06',
    tiene_beca: true,
    tipo_beca: 'Apoyo Departamental - DEDU',
    porcentaje_beca: 50,
    promedio_academico: 9.1,
    puntos_beca_meta_cuatrimestral: 1000,
    es_becario_departamental: true,
    departamento_beca: 'DEDU (Dirección de Extensión y Difusión)',
    horas_departamentales_semanales: 10,
    cumplimiento_departamental_acreditado: true,
    fecha_acreditacion_departamental: '2026-08-16',
    puntos_departamentales_otorgados: 1000,
    created_at: '2020-08-15T09:00:00Z',
  },
  {
    id: 'usr-dedu-01',
    matricula: 'DEDU-2091',
    nombre: 'Lic. Paulina',
    apellidos: 'García Davis',
    carrera: 'Dirección de Extensión y Difusión Universitaria (DEDU)',
    periodo_ingreso: '2020-2',
    email: 'dedu.difusion@unipaz.edu.mx',
    role: 'extension',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    qr_secret: 'dedu-unipaz-events-key-002',
    created_at: '2020-08-01T08:00:00Z',
  },
  {
    id: 'usr-staff-01',
    matricula: 'ADM-1044',
    nombre: 'Mtro. Roberto',
    apellidos: 'Ojeda Lucero',
    carrera: 'Administración General & Comité de Becas',
    periodo_ingreso: '2019-1',
    email: 'pfi.coordinacion@unipaz.edu.mx',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    qr_secret: 'admin-unipaz-pfi-master-key-001',
    created_at: '2019-01-01T08:00:00Z',
  },
];

export const MOCK_EVENTS: PFIEvent[] = [
  // PVC Obligatorios (25h c/u)
  {
    id: 'evt-pvc-01',
    titulo: 'PVC I: Iniciando mis sueños',
    descripcion: 'Taller formativo de autoexploración vocacional, fijación de metas profesionales y proyecto de vida inicial.',
    categoria: 'PVC',
    subcategoria: 'Plan de Vida y Carrera',
    modalidad: 'presencial',
    fecha_evento: '2026-08-25',
    hora_inicio: '09:00',
    hora_fin: '13:00',
    horas_pfi: 25.00,
    puntos_beca: 250,
    cupo_maximo: 60,
    cupo_ocupado: 45,
    ubicacion: 'Aula Magna UNIPAZ, Edificio A',
    activo: true,
  },
  {
    id: 'evt-pvc-02',
    titulo: 'PVC II: Ahí la llevo',
    descripcion: 'Consolidación de competencias laborales, perfil de egreso, autogestión y resiliencia profesional.',
    categoria: 'PVC',
    subcategoria: 'Plan de Vida y Carrera',
    modalidad: 'hibrido',
    fecha_evento: '2026-09-12',
    hora_inicio: '10:00',
    hora_fin: '14:00',
    horas_pfi: 25.00,
    puntos_beca: 250,
    cupo_maximo: 80,
    cupo_ocupado: 62,
    enlace_virtual: 'https://meet.google.com/unipaz-pvc2',
    otp_online_code: 'PVC202',
    ubicacion: 'Auditorio Central y Google Meet',
    activo: true,
  },
  {
    id: 'evt-pvc-03',
    titulo: 'PVC III: Ya casi',
    descripcion: 'Transición al campo laboral, ética profesional, marca personal, inserción laboral y red de contactos.',
    categoria: 'PVC',
    subcategoria: 'Plan de Vida y Carrera',
    modalidad: 'presencial',
    fecha_evento: '2026-10-05',
    hora_inicio: '16:00',
    hora_fin: '20:00',
    horas_pfi: 25.00,
    puntos_beca: 250,
    cupo_maximo: 50,
    cupo_ocupado: 38,
    ubicacion: 'Sala de Seminarios Posgrado',
    activo: true,
  },

  // Taller de Liderazgo Obligatorio (10h)
  {
    id: 'evt-lid-01',
    titulo: 'Taller de Liderazgo y Promoción Social: Equidad e Inclusión',
    descripcion: 'Formación en habilidades directivas con enfoque en inclusión social, derechos humanos y perspectiva de género.',
    categoria: 'Taller Liderazgo',
    subcategoria: 'Liderazgo y Equidad',
    modalidad: 'presencial',
    fecha_evento: '2026-08-30',
    hora_inicio: '15:00',
    hora_fin: '19:00',
    horas_pfi: 10.00,
    puntos_beca: 150,
    cupo_maximo: 45,
    cupo_ocupado: 40,
    ubicacion: 'Centro de Innovación y Liderazgo',
    activo: true,
  },

  // Talleres Extracurriculares (16.67h c/u - 3 requeridos = 50h)
  {
    id: 'evt-ext-01',
    titulo: 'Taller Deportivo: Acondicionamiento y Voleibol de Playa',
    descripcion: 'Desarrollo de habilidades motrices, disciplina deportiva y trabajo en equipo universitario.',
    categoria: 'Taller Extracurricular',
    subcategoria: 'Deportes',
    modalidad: 'presencial',
    fecha_evento: '2026-08-20',
    hora_inicio: '08:00',
    hora_fin: '12:00',
    horas_pfi: 16.67,
    puntos_beca: 200,
    cupo_maximo: 30,
    cupo_ocupado: 28,
    ubicacion: 'Canchas Deportivas del Campus',
    activo: true,
  },
  {
    id: 'evt-ext-02',
    titulo: 'Taller Cultural: Expresión Teatral y Oratoria Escénica',
    descripcion: 'Técnicas de modulación de voz, lenguaje corporal y desinhibición para hablar en público.',
    categoria: 'Taller Extracurricular',
    subcategoria: 'Cultura y Arte',
    modalidad: 'presencial',
    fecha_evento: '2026-09-02',
    hora_inicio: '16:00',
    hora_fin: '20:00',
    horas_pfi: 16.67,
    puntos_beca: 200,
    cupo_maximo: 35,
    cupo_ocupado: 30,
    ubicacion: 'Foro Cultural Universitario',
    activo: true,
  },
  {
    id: 'evt-ext-03',
    titulo: 'Taller Extracurricular: Ajedrez Estratégico y Toma de Decisiones',
    descripcion: 'Pensamiento táctico, análisis de escenarios complejos y concentración bajo presión.',
    categoria: 'Taller Extracurricular',
    subcategoria: 'Desarrollo Intelectual',
    modalidad: 'presencial',
    fecha_evento: '2026-09-18',
    hora_inicio: '14:00',
    hora_fin: '18:00',
    horas_pfi: 16.67,
    puntos_beca: 200,
    cupo_maximo: 25,
    cupo_ocupado: 22,
    ubicacion: 'Biblioteca Central UNIPAZ - Sala de Lectura',
    activo: true,
  },

  // Investigación (100h)
  {
    id: 'evt-inv-01',
    titulo: 'Coloquio de Investigación: Publicación de Artículo Científico Arbitrado',
    descripcion: 'Reconocimiento a autores de proyectos y ponencias de investigación en congresos indexados.',
    categoria: 'Investigación',
    subcategoria: 'Producción Académica',
    modalidad: 'presencial',
    fecha_evento: '2026-09-25',
    hora_inicio: '10:00',
    hora_fin: '14:00',
    horas_pfi: 100.00,
    puntos_beca: 500,
    cupo_maximo: 20,
    cupo_ocupado: 12,
    ubicacion: 'Auditorio de Posgrado',
    activo: true,
  },

  // Club Anual (33.34h)
  {
    id: 'evt-clb-01',
    titulo: 'Club Anual de Debate y Argumentación Jurídica UNIPAZ',
    descripcion: 'Ciclo anual de análisis de casos jurisprudenciales y torneos interuniversitarios de oratoria.',
    categoria: 'Club Anual',
    subcategoria: 'Clubes Universitarios',
    modalidad: 'presencial',
    fecha_evento: '2026-09-08',
    hora_inicio: '17:00',
    hora_fin: '19:00',
    horas_pfi: 33.34,
    puntos_beca: 300,
    cupo_maximo: 40,
    cupo_ocupado: 35,
    ubicacion: 'Sala de Juicios Orales',
    activo: true,
  },

  // Simposios y Congresos (5.56h)
  {
    id: 'evt-sim-01',
    titulo: 'Simposio Internacional de Sustentabilidad y Mares de BCS',
    descripcion: 'Conferencias magistrales con investigadores internacionales sobre conservación marina y economía azul.',
    categoria: 'Simposio',
    subcategoria: 'Congresos Académicos',
    modalidad: 'hibrido',
    fecha_evento: '2026-09-15',
    hora_inicio: '09:00',
    hora_fin: '14:30',
    horas_pfi: 5.56,
    puntos_beca: 180,
    permite_staff: true,
    cupo_staff: 5,
    horas_staff: 10.0,
    puntos_beca_staff: 100,
    cupo_maximo: 200,
    cupo_ocupado: 145,
    enlace_virtual: 'https://youtube.com/unipaz/simposio2026',
    otp_online_code: 'MAR26X',
    ubicacion: 'Teatro de la Ciudad y Transmisión en Vivo',
    activo: true,
  },

  // Jornadas Sociales (5.00h)
  {
    id: 'evt-jor-01',
    titulo: 'Jornada Universitaria de Salud Comunitaria y Asesoría Legal',
    descripcion: 'Brigada de atención directa en colonias vulnerables de La Paz, BCS.',
    categoria: 'Jornada Social',
    subcategoria: 'Servicio Comunitario',
    modalidad: 'presencial',
    fecha_evento: '2026-09-22',
    hora_inicio: '08:00',
    hora_fin: '13:00',
    horas_pfi: 5.00,
    puntos_beca: 120,
    cupo_maximo: 50,
    cupo_ocupado: 48,
    ubicacion: 'Parque Comunitario Los Olivos',
    activo: true,
  },

  // Cine Club / Café Literario (2.50h)
  {
    id: 'evt-cin-01',
    titulo: 'Cine Debate: Inteligencia Artificial, Ética y Futuro del Trabajo',
    descripcion: 'Proyección y análisis crítico guiado por catedráticos de filosofía y ciencias computacionales.',
    categoria: 'Cine Club',
    subcategoria: 'Cine Club',
    modalidad: 'presencial',
    fecha_evento: '2026-08-28',
    hora_inicio: '18:00',
    hora_fin: '20:30',
    horas_pfi: 2.50,
    puntos_beca: 60,
    cupo_maximo: 70,
    cupo_ocupado: 60,
    ubicacion: 'Cine Foro UNIPAZ',
    activo: true,
  },

  // Foros y Conferencias (2.00h)
  {
    id: 'evt-for-01',
    titulo: 'Foro: Salud Mental Universitaria y Manejo del Estrés Académico',
    descripcion: 'Estrategias de autorregulación emocional y bienestar psicológico impartido por psicoterapeutas.',
    categoria: 'Foro',
    subcategoria: 'Salud y Bienestar',
    modalidad: 'online',
    fecha_evento: '2026-09-04',
    hora_inicio: '17:00',
    hora_fin: '19:00',
    horas_pfi: 2.00,
    puntos_beca: 80,
    cupo_maximo: 300,
    cupo_ocupado: 210,
    enlace_virtual: 'https://meet.google.com/unipaz-salud-mental',
    otp_online_code: 'PSICO9',
    ubicacion: 'Plataforma Virtual Google Meet',
    activo: true,
  },

  // Campañas de Voluntariado (1.00h)
  {
    id: 'evt-cam-01',
    titulo: 'Campaña Universitaria de Reforestación y Cuidado del Agua',
    descripcion: 'Plantación de especies endémicas y sensibilización sobre la reserva hídrica de La Paz.',
    categoria: 'Campaña',
    subcategoria: 'Ecología y Voluntariado',
    modalidad: 'presencial',
    fecha_evento: '2026-08-29',
    hora_inicio: '08:00',
    hora_fin: '09:00',
    horas_pfi: 1.00,
    puntos_beca: 50,
    cupo_maximo: 100,
    cupo_ocupado: 75,
    ubicacion: 'Jardín Botánico UNIPAZ',
    activo: true,
  },
];

// Asistencias iniciales de los estudiantes muestra
export const MOCK_ATTENDANCES: EventAttendance[] = [
  // --- Sofía Méndez (420 hrs - Acreditada Satisfactorio) ---
  {
    id: 'att-sofia-01',
    student_id: 'usr-student-01',
    event_id: 'evt-pvc-01',
    status: 'asistio',
    check_in_timestamp: '2025-09-10T09:00:00Z',
    check_out_timestamp: '2025-09-10T13:00:00Z',
    horas_acreditadas: 25.00,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-02',
    student_id: 'usr-student-01',
    event_id: 'evt-pvc-02',
    status: 'asistio',
    check_in_timestamp: '2026-02-12T10:00:00Z',
    check_out_timestamp: '2026-02-12T14:00:00Z',
    horas_acreditadas: 25.00,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-03',
    student_id: 'usr-student-01',
    event_id: 'evt-pvc-03',
    status: 'asistio',
    check_in_timestamp: '2026-05-15T16:00:00Z',
    check_out_timestamp: '2026-05-15T20:00:00Z',
    horas_acreditadas: 25.00,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-04',
    student_id: 'usr-student-01',
    event_id: 'evt-lid-01',
    status: 'asistio',
    check_in_timestamp: '2025-11-20T15:00:00Z',
    check_out_timestamp: '2025-11-20T19:00:00Z',
    horas_acreditadas: 10.00,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-05',
    student_id: 'usr-student-01',
    event_id: 'evt-ext-01',
    status: 'asistio',
    check_in_timestamp: '2025-10-05T08:00:00Z',
    check_out_timestamp: '2025-10-05T12:00:00Z',
    horas_acreditadas: 16.67,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-06',
    student_id: 'usr-student-01',
    event_id: 'evt-ext-02',
    status: 'asistio',
    check_in_timestamp: '2026-03-01T16:00:00Z',
    check_out_timestamp: '2026-03-01T20:00:00Z',
    horas_acreditadas: 16.67,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-07',
    student_id: 'usr-student-01',
    event_id: 'evt-ext-03',
    status: 'asistio',
    check_in_timestamp: '2026-04-10T14:00:00Z',
    check_out_timestamp: '2026-04-10T18:00:00Z',
    horas_acreditadas: 16.67,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-08',
    student_id: 'usr-student-01',
    event_id: 'evt-inv-01',
    status: 'asistio',
    check_in_timestamp: '2026-06-01T10:00:00Z',
    check_out_timestamp: '2026-06-01T14:00:00Z',
    horas_acreditadas: 100.00,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-09',
    student_id: 'usr-student-01',
    event_id: 'evt-clb-01',
    status: 'asistio',
    check_in_timestamp: '2025-12-01T17:00:00Z',
    check_out_timestamp: '2025-12-01T19:00:00Z',
    horas_acreditadas: 33.34,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-10',
    student_id: 'usr-student-01',
    event_id: 'evt-inv-01', // segundo proyecto
    status: 'asistio',
    check_in_timestamp: '2026-07-15T10:00:00Z',
    check_out_timestamp: '2026-07-15T14:00:00Z',
    horas_acreditadas: 100.00,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-11',
    student_id: 'usr-student-01',
    event_id: 'evt-sim-01',
    status: 'asistio',
    check_in_timestamp: '2026-05-20T09:00:00Z',
    check_out_timestamp: '2026-05-20T14:30:00Z',
    horas_acreditadas: 5.56,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-12',
    student_id: 'usr-student-01',
    event_id: 'evt-jor-01',
    status: 'asistio',
    check_in_timestamp: '2026-06-10T08:00:00Z',
    check_out_timestamp: '2026-06-10T13:00:00Z',
    horas_acreditadas: 5.00,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-13',
    student_id: 'usr-student-01',
    event_id: 'evt-cin-01',
    status: 'asistio',
    check_in_timestamp: '2026-07-01T18:00:00Z',
    check_out_timestamp: '2026-07-01T20:30:00Z',
    horas_acreditadas: 2.50,
    validado_por: 'usr-staff-01',
  },
  {
    id: 'att-sofia-14',
    student_id: 'usr-student-01',
    event_id: 'evt-for-01',
    status: 'asistio',
    check_in_timestamp: '2026-07-10T17:00:00Z',
    check_out_timestamp: '2026-07-10T19:00:00Z',
    horas_acreditadas: 2.00,
    validado_por: 'usr-staff-01',
  },

  // --- Carlos Valenzuela (745 hrs - Sobresaliente) ---
  {
    id: 'att-carlos-01',
    student_id: 'usr-student-02',
    event_id: 'evt-pvc-01',
    status: 'asistio',
    horas_acreditadas: 25.00,
  },
  {
    id: 'att-carlos-02',
    student_id: 'usr-student-02',
    event_id: 'evt-pvc-02',
    status: 'asistio',
    horas_acreditadas: 25.00,
  },
  {
    id: 'att-carlos-03',
    student_id: 'usr-student-02',
    event_id: 'evt-pvc-03',
    status: 'asistio',
    horas_acreditadas: 25.00,
  },
  {
    id: 'att-carlos-04',
    student_id: 'usr-student-02',
    event_id: 'evt-lid-01',
    status: 'asistio',
    horas_acreditadas: 10.00,
  },
  {
    id: 'att-carlos-05',
    student_id: 'usr-student-02',
    event_id: 'evt-ext-01',
    status: 'asistio',
    horas_acreditadas: 16.67,
  },
  {
    id: 'att-carlos-06',
    student_id: 'usr-student-02',
    event_id: 'evt-ext-02',
    status: 'asistio',
    horas_acreditadas: 16.67,
  },
  {
    id: 'att-carlos-07',
    student_id: 'usr-student-02',
    event_id: 'evt-ext-03',
    status: 'asistio',
    horas_acreditadas: 16.67,
  },
  {
    id: 'att-carlos-08',
    student_id: 'usr-student-02',
    event_id: 'evt-inv-01',
    status: 'asistio',
    horas_acreditadas: 100.00,
  },
  {
    id: 'att-carlos-09',
    student_id: 'usr-student-02',
    event_id: 'evt-inv-01',
    status: 'asistio',
    horas_acreditadas: 100.00,
  },
  {
    id: 'att-carlos-10',
    student_id: 'usr-student-02',
    event_id: 'evt-inv-01',
    status: 'asistio',
    horas_acreditadas: 100.00,
  },
  {
    id: 'att-carlos-11',
    student_id: 'usr-student-02',
    event_id: 'evt-inv-01',
    status: 'asistio',
    horas_acreditadas: 100.00,
  },
  {
    id: 'att-carlos-12',
    student_id: 'usr-student-02',
    event_id: 'evt-inv-01',
    status: 'asistio',
    horas_acreditadas: 100.00,
  },
  {
    id: 'att-carlos-13',
    student_id: 'usr-student-02',
    event_id: 'evt-clb-01',
    status: 'asistio',
    horas_acreditadas: 33.34,
  },
  {
    id: 'att-carlos-14',
    student_id: 'usr-student-02',
    event_id: 'evt-clb-01',
    status: 'asistio',
    horas_acreditadas: 33.34,
  },
  {
    id: 'att-carlos-15',
    student_id: 'usr-student-02',
    event_id: 'evt-sim-01',
    status: 'asistio',
    horas_acreditadas: 5.56,
  },

  // --- Mariana Castro (210 hrs - En Proceso / No Satisfactorio) ---
  {
    id: 'att-mariana-01',
    student_id: 'usr-student-03',
    event_id: 'evt-pvc-01',
    status: 'asistio',
    horas_acreditadas: 25.00,
  },
  {
    id: 'att-mariana-02',
    student_id: 'usr-student-03',
    event_id: 'evt-pvc-02',
    status: 'asistio',
    horas_acreditadas: 25.00,
  },
  {
    id: 'att-mariana-03',
    student_id: 'usr-student-03',
    event_id: 'evt-lid-01',
    status: 'asistio',
    horas_acreditadas: 10.00,
  },
  {
    id: 'att-mariana-04',
    student_id: 'usr-student-03',
    event_id: 'evt-ext-01',
    status: 'asistio',
    horas_acreditadas: 16.67,
  },
  {
    id: 'att-mariana-05',
    student_id: 'usr-student-03',
    event_id: 'evt-clb-01',
    status: 'asistio',
    horas_acreditadas: 33.34,
  },
  {
    id: 'att-mariana-06',
    student_id: 'usr-student-03',
    event_id: 'evt-inv-01',
    status: 'asistio',
    horas_acreditadas: 100.00,
  },
];

export const MOCK_AUDIT_LOGS: StudentAuditEntry[] = [
  {
    id: 'aud-001',
    student_id: 'usr-student-01',
    timestamp: '2026-08-15T10:30:00Z',
    autor_id: 'usr-staff-01',
    autor_nombre: 'Mtro. Roberto Ojeda Lucero',
    autor_rol: 'admin',
    categoria: 'solicitud_beca',
    accion: 'Dictamen Oficial de Beca de Excelencia Académica',
    detalles: 'El Comité de Becas aprobó el dictamen formal con 50% de exención por promedio cuatrimestral de 9.65 y cumplimiento íntegro de requisitos.',
    valor_anterior: 'En Evaluación',
    valor_nuevo: '50% Excelencia Académica (Aprobada)',
    metadata: { periodo: '187 (Mayo - Agosto 2026)', promedio: 9.65 },
  },
  {
    id: 'aud-002',
    student_id: 'usr-student-01',
    timestamp: '2026-08-16T12:00:00Z',
    autor_id: 'usr-dedu-01',
    autor_nombre: 'Lic. Paulina García Davis',
    autor_rol: 'extension',
    categoria: 'validacion_actividad',
    accion: 'Acreditación Extemporánea de Actividad Formativa (PVC I)',
    detalles: 'Se validó la asistencia presencial y bitácora de autoexploración vocacional tras verificación de lista física de asistencia con firma del instructor.',
    valor_anterior: '0.0 hrs PFI',
    valor_nuevo: '25.0 hrs PFI (Acreditado)',
    metadata: { evento_id: 'evt-pvc-01', instructor: 'Mtra. Lucero' },
  },
  {
    id: 'aud-003',
    student_id: 'usr-student-01',
    timestamp: '2026-08-18T16:45:00Z',
    autor_id: 'usr-staff-01',
    autor_nombre: 'Mtro. Roberto Ojeda Lucero',
    autor_rol: 'admin',
    categoria: 'comentario_expediente',
    accion: 'Observación y Cotejo de Documentación en Ventanilla',
    detalles: 'Estudiante presentó comprobante de domicilio e informe de metas cuatrimestrales debidamente sellados. Expediente al corriente.',
    valor_anterior: undefined,
    valor_nuevo: 'Expediente Verificado',
  },
  {
    id: 'aud-004',
    student_id: 'usr-student-02',
    timestamp: '2026-08-10T09:15:00Z',
    autor_id: 'usr-staff-01',
    autor_nombre: 'Mtro. Roberto Ojeda Lucero',
    autor_rol: 'admin',
    categoria: 'renovacion_beca',
    accion: 'Ratificación Cuatrimestral de Beca Deportiva (75%)',
    detalles: 'Ratificación aprobada tras constancia de representación deportiva del selectivo Garzas UNIPAZ y acreditación de 1,000 puntos PFI.',
    valor_anterior: 'Pendiente de Refrendo',
    valor_nuevo: 'Ratificada 75%',
  },
  {
    id: 'aud-005',
    student_id: 'usr-student-02',
    timestamp: '2026-08-14T11:20:00Z',
    autor_id: 'usr-dedu-01',
    autor_nombre: 'Lic. Paulina García Davis',
    autor_rol: 'extension',
    categoria: 'justificacion_asistencia',
    accion: 'Aprobación de Justificante por Competencia Deportiva',
    detalles: 'Se aprobó justificante con oficio institucional de la Coordinación de Deportes para el Foro de Emprendimiento.',
    valor_anterior: 'Inasistencia Registrada',
    valor_nuevo: 'Justificada con Reconocimiento de Horas',
  },
  {
    id: 'aud-006',
    student_id: 'usr-student-04',
    timestamp: '2026-08-15T14:30:00Z',
    autor_id: 'usr-staff-01',
    autor_nombre: 'Mtro. Roberto Ojeda Lucero',
    autor_rol: 'admin',
    categoria: 'cambio_beca',
    accion: 'Asignación de Servicio Becario en Biblioteca',
    detalles: 'Asignación de 10 horas semanales de apoyo en digitalización y catálogo bibliográfico con 1,000 puntos formativos acreditados al término.',
    valor_anterior: 'Beca Institucional 30%',
    valor_nuevo: 'Beca Departamental 50% (Biblioteca)',
  },
];
